# Travis Continuous Integration Configuration File For ROS Control Projects
# Author: Dave Coleman
language: generic
services:
  - docker

notifications:
  email:
    recipients:
      - nicola.pedrocchi@stiima.cnr.com
    on_success: change #[always|never|change] # default: change
    on_failure: change #[always|never|change] # default: always
env:
  global:
    - UPSTREAM_WORKSPACE='cnr_control_toolbox.rosinstall -cnr_control_toolbox'
  matrix:
    - ROS_DISTRO=noetic ROS_REPO=ros
    - ROS_DISTRO=noetic ROS_REPO=ros-testing
    - ROS_DISTRO=noetic DOWNSTREAM_WORKSPACE='ros_control.rosinstall -ros_control -realtime_tools -control_toolbox -control_msgs'
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh
