<?xml version="1.0"?>
<package format="2">
  <name>cnr_control_toolbox</name>
  <version>0.1.0</version>
  <description>The CNR control toolbox package</description>

  <maintainer email="manuel.beschi@unibs.it">Manuel Beschi</maintainer>
  <license>BSM</license>

  <buildtool_depend>cmake</buildtool_depend>

</package>
